import localFont from "next/font/local";
import "../globals.css";
import Header from "@/app/[lang]/components/Header";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "LWS XSTREAM",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal, params }) {
  return (
    <html lang="en">
      <body
        className='bg-color-bg text-white font-exo'
      >
        <div className="container mx-auto px-4 py-4">
          <Header params={params} />
          {modal}
          {children}
        </div>
      </body>
    </html>
  );
}
